### ISSUE TITLE
[BUG] gray screen on version selection

### ISSUE THREAD

**Issue by Matz-a** [mrquantumoff/mcmodpackmanager_reborn#11]
**Describe the bug**

**To Reproduce**
1. Go to 'create modpack'
2. Click on 'select version'

**Your device**
 - OS: nobara linux 38
 - i tried the latest fedora and latest release here on github

**Additional context**
error received in terminal upon bug encounter:
flutter: RangeError (length): Invalid value: Valid value range is empty: 0)

**Comment by mrquantumoff** [comment]
Hello, I've been able to reproduce the bug, I'm working on a way to fix it right now.

**Comment by mrquantumoff** [comment]
I found a way to fix it. The fix will be released together with v23.10
