### ISSUE TITLE
[FEATURE REQUEST] Change "Download" Button to "Downloaded" when mod is already installed

### ISSUE THREAD

**Issue by GOseUser** [mrquantumoff/mcmodpackmanager_reborn#13]
Change "Download" Button to "Downloaded" when mod is already installed.
from:
![image](https://github.com/user-attachments/assets/faa16866-8a36-4568-bc8e-cef965d7bf9a)
to something like:
![image](https://github.com/user-attachments/assets/eefab0c6-436e-4f2c-b8a3-d5cfd13d2dcb)

**Comment by mrquantumoff** [comment]
Thank you for the feedback, I'll attempt to implement this feature as soon as I can

**Comment by mrquantumoff** [comment]
Implemented.
