### ISSUE TITLE
[BUG] grey window when running 

### ISSUE THREAD

**Issue by Mart994** [mrquantumoff/mcmodpackmanager_reborn#3]
**Describe the bug**
when I run the program, a grey window appears and I can't do anything

**To Reproduce**
1. Run the app
2. See error

**Screenshots**
![Captura desde 2023-04-08 01-29-11](https://user-images.githubusercontent.com/38144617/230703222-fa7f400d-d8c9-457a-9841-a4866bf96e35.png)

**Your device**
 - OS: Fedora 37 workstation (up to date)
- `Linux fedora 6.2.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:31:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Version of the app: Flatpak version from Flathub, 7.14.1

**Additional context**
text displayed when I run on console:

```
$flatpak run dev.mrquantumoff.mcmodpackmanager

(process:2): GLib-GObject-CRITICAL **: 01:27:37.231: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'dev.mrquantumoff.mcmodpackmaager'
flutter: mrquantumoff/mcmodpackmanager_reborn/v7.14.1 (mrquantumoff.dev)
flutter: System locale is "es"
flutter: System locale is "es"
flutter: System locale is "es"
flutter: LateInitializationError: Field 'locale' has not been initialized.
flutter: 
flutter: dynamic_color: Accent color detected.
flutter: System locale is "es"
flutter: System locale is "es"
flutter: System locale is "es"
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

Maybe it's a problem because the location/language of my linux is in Spanish?

**Comment by mrquantumoff** [comment]
Thanks for reporting the problem, I will attempt to fix it as soon as I can.

**Comment by mrquantumoff** [comment]
I think I fixed the issue, it ususally takes flathub a few hours to update the app, but if you want you can use this build in order to check out 7.14.2
```bash
flatpak install --user https://dl.flathub.org/build-repo/16168/dev.mrquantumoff.mcmodpackmanager.flatpakref
```
