### ISSUE TITLE
The App doesn't work

### ISSUE THREAD

**Issue by Kawasofft** [mrquantumoff/mcmodpackmanager_reborn#5]
I'm on Linux Mint 20.3
When starting the app, nothing appends (in the older versions disponible on the official App store, just a gray window pops up but stay gray). Is it normal ?
![edrt](https://github.com/mrquantumoff/mcmodpackmanager_reborn/assets/85878841/a09eb29d-1765-41b5-9a08-e2fc7b9714a5)

**Comment by mrquantumoff** [comment]
Please open the app via the terminal and post the output

**Comment by mrquantumoff** [comment]
Also please specify the app version, since you are installing the app through the linux mint store, I assume you are using flatpak

**Comment by Kawasofft** [comment]
If I use the 2.6.0 version of the app, I get this : 
./io.github.mrquantumoff.mcmodpackmanager.desktop: line 1: [Desktop : command not found
./io.github.mrquantumoff.mcmodpackmanager.desktop: line 3: run : command not found
./io.github.mrquantumoff.mcmodpackmanager.desktop: line 5: Modpack: command not found
./io.github.mrquantumoff.mcmodpackmanager.desktop: line 8: X-Flatpak=io.github.mrquantumoff.mcmodpackmanager : command not found

If I use the one on the flathub page, I get this which is the same (the app version doesn't appear) : 
./dev.mrquantumoff.mcmodpackmanager.desktop: line 1: [Desktop: command not found
./dev.mrquantumoff.mcmodpackmanager.desktop: line 3: run : command not found
./dev.mrquantumoff.mcmodpackmanager.desktop: line 6: Modpack: command not found
./dev.mrquantumoff.mcmodpackmanager.desktop: line 10: X-Flatpak=dev.mrquantumoff.mcmodpackmanager : command not found

**Comment by mrquantumoff** [comment]
Please update to the latest version, 2.6.0 is outdated.

**Comment by Kawasofft** [comment]
I already did it using the second one available on your website page which is the v8.4.0. And nothing changes. It's even worse.... The 2.6.0 brings up a gray window while the v8.4.0 starts the app and immediately close it.

**Comment by mrquantumoff** [comment]
Sorry, I might have misunderstood you. I believe that this is a flatpak problem. I was running the app on opensuse tumbleweed and pop os the other day and everything was working fine. This isn't really related to the app, but I suggest updating to mint 21.1, 20.3 may have a broken flatpak version.

**Comment by Kawasofft** [comment]
ok, maybe this may help you ?

(process:2): GLib-GObject-CRITICAL **: 10:56:16.716: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'dev.mrquantumoff.mcmodpackmaager'
Gtk-Message: 10:56:16.721: Failed to load module "xapp-gtk3-module"
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

**Comment by Kawasofft** [comment]
i get it when using this command : /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mcmodpackmanager_reborn --file-forwarding dev.mrquantumoff.mcmodpackmanager @@u %u @@

**Comment by mrquantumoff** [comment]
Have you changed the permissions for the app?

**Comment by Kawasofft** [comment]
no

**Comment by mrquantumoff** [comment]
Can you try to run just ``flatpak run dev.mrquantumoff.mcmodpackmanager``

**Comment by Kawasofft** [comment]
![image](https://github.com/mrquantumoff/mcmodpackmanager_reborn/assets/85878841/11b4fad3-a382-47a0-ac9d-3f472fa937f4)
wtf

**Comment by Kawasofft** [comment]
oh my bad, you made a mistake in your message.
if i enter flatpak run dev.mrquantumoff.mcmodpackmanager, i get the same thing : 

(process:2): GLib-GObject-CRITICAL **: 11:43:35.061: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'dev.mrquantumoff.mcmodpackmaager'
Gtk-Message: 11:43:35.067: Failed to load module "xapp-gtk3-module"
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

**Comment by mrquantumoff** [comment]
I've looked into this issue and found out that this is a flutter/ubuntu/nvidia problem, it's still an open issue https://github.com/flutter/flutter/issues/85460
